server {
    listen 80;

    root /usr/share/nginx/html;

    location = /know_your_values {
        return 301 /know_your_values/;
    }

    location /know_your_values/ {
        index index.html;
        try_files $uri $uri/ /know_your_values/index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
    }

    location / {
        return 301 /know_your_values/;
    }

    error_page 404 /know_your_values/index.html;
}
