server {
    listen 80;

    location = / {
        return 301 /know_your_values/;
    }

    location /know_your_values/ {
        alias /usr/share/nginx/html/know_your_values/;
        index index.html;
        try_files $uri $uri/ /know_your_values/index.html;
    }

    # Redirect any other traffic to the subpath
    location / {
        return 301 /know_your_values/;
    }

    error_page 404 /know_your_values/index.html;
}
