name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: bunker.mantracare.com
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: bunker.mantracare.com/lovable/know_your_value:1.0
          build-args: |
            VITE_DATABASE_URL=postgresql://neondb_owner:npg_kflMt85LnsNu@ep-solitary-glitter-a1419gib-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
            VITE_NEON_PROJECT_ID=ancient-queen-75365745
            VITE_NEON_API_KEY=napi_ewlzpqv336e41usn232duvfax8vu1g5g37ozlz8x53eic18pjsyg30vqqorexfav
